# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
    host: 127.0.0.1
    port: 3306
    adapter: mysql2
    encoding: utf8
    database: webscan
    pool: 50
    username: root
    password: root
    socket: /var/run/mysqld/mysqld.sock 

development:
    <<: *default 
    database: webscan

test:
  <<: *default
  database: webscan_test

production:
  <<: *default
  database: webscan_product
